---
unifi_network_application_version: 8.1.113-ls36
unifi_mongodb_version: 4.4.10
unifi_workdir: /opt/unifi
unifi_mongodb_password: changemeifyoucareaboutsecurity
unifi_mongodb_user: unifi
unifi_mongodb_dbname: unifi
unifi_mongodb_workdir: '{{ unifi_workdir }}/mongodb'
unifi_app_workdir: '{{ unifi_workdir }}/unifi-app'
